            TableModelColumn { display: "00:00" }
            TableModelColumn { display: "01:00" }
            TableModelColumn { display: "02:00" }
            TableModelColumn { display: "03:00" }
            TableModelColumn { display: "04:00" }
            TableModelColumn { display: "05:00" }
            TableModelColumn { display: "06:00" }
            TableModelColumn { display: "07:00" }
            TableModelColumn { display: "08:00" }
            TableModelColumn { display: "09:00" }
            TableModelColumn { display: "10:00" }
            TableModelColumn { display: "11:00" }          
            TableModelColumn { display: "12:00" }
            TableModelColumn { display: "13:00" }
            TableModelColumn { display: "14:00" }
            TableModelColumn { display: "15:00" }
            TableModelColumn { display: "16:00" }
            TableModelColumn { display: "17:00" }
            TableModelColumn { display: "18:00" }
            TableModelColumn { display: "19:00" }
            TableModelColumn { display: "20:00" }
            TableModelColumn { display: "21:00" }
            TableModelColumn { display: "22:00" }      
            TableModelColumn { display: "23:00" }    